// src/app/layout.tsx
import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Admin Dashboard',
  description: 'Student Management System Admin Panel',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}




// src/app/admin/layout.tsx
/*import Link from 'next/link';
import React from 'react';

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen bg-white text-[#121717] font-sans">
      {/* Sidebar */
      /*<div className="w-80 bg-[#f1f4f4] p-6 flex flex-col justify-between">
        <div>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-center bg-cover rounded-full bg-[url('/favicon.ico')]"></div>
            <h1 className="text-lg font-medium">Acme University</h1>
          </div>
          <ul className="space-y-3">
            <li><Link href="/admin" className="block py-2 px-3 rounded-xl hover:bg-gray-200">Dashboard</Link></li>
            <li><Link href="/admin/users" className="block py-2 px-3 rounded-xl hover:bg-gray-200">Users</Link></li>
            <li><Link href="/admin/courses" className="block py-2 px-3 rounded-xl hover:bg-gray-200">Courses</Link></li>
            <li><Link href="/admin/logs" className="block py-2 px-3 rounded-xl hover:bg-gray-200">Logs</Link></li>
            <li><Link href="/admin/analytics" className="block py-2 px-3 rounded-xl hover:bg-gray-200">Analytics</Link></li>
          </ul>
        </div>
        <p className="text-sm text-gray-600">© 2025 Acme University</p>
      </div>

      {/* Main Content */
      /*<main className="flex-1 p-6 overflow-auto">{children}</main>
    </div>
  );
}
*/

/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/
